# Permalinks
permalink:        /:title/

# Setup
title:            Josh Buchea
tagline:          Software Developer
url:              https://joshbuchea.com
baseurl:          https://joshbuchea.com/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:           Josh Buchea
  url:            https://twitter.com/joshbuchea
  email:          hello@joshbuchea.com
  twitter:        https://twitter.com/joshbuchea
  github:         https://github.com/joshbuchea
  appstore:       https://itunes.apple.com/developer/joshua-buchea/id469778668?mt=8&at=11l7ss&ct=joshbucheadotcom
  googleplay:      https://play.google.com/store/apps/developer?id=Josh+Buchea

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/joshbuchea/com.joshbuchea
